import  Premium1  from "./Premium1.jpg"
import  Premium2  from "./Premium2.jpg"
import  Premium3  from "./Premium3.jpg"
import  TurquesaPortada  from "./TURQUESAPORTADA2.jpg"
import  Turquesa12  from "./TURQUESA12.jpg"
import  Turquesa2  from "./TURQUESA2.jpg"
// import  Turquesa3  from "./TURQUESA3.jpg"
import  RojoPortada  from "./ROJOPORTADA.jpg"
import  Rojo1  from "./ROJO1.jpg"
import  Rojo2  from "./ROJO2.jpg"
import  Rojo3  from "./ROJO3.jpg"
import  CelestePortada  from "./CELESTEPORTADA.jpg"
import  Celeste1  from "./CELESTE1.jpg"
import  Celeste2  from "./CELESTE2.jpg"
import  Celeste3  from "./CELESTE3.jpg"
export const gazebos = [
     {
      id: 4,
      name: "Gazebo Modelo Premium",
      image: "http://res.cloudinary.com/djsqt7j6v/image/upload/v1728073268/eopdkih3mum4kpky2juu.jpg",
      description: "Modelo Premium:\n-Tela elastica 3x3m (armado queda de 5x5m aprox)\n-4 Parantes de aluminio regulables (2,25m altura máxima)\n-4 estacas tirabuzón\n-4 bolsas de contrapeso\n- bolso de transporte\n\nDescuentos pagando por efectivo/transferencia.\n\n•Multiforma: su toldo elástico, y sus parantes regulables en altura te permitirán darle la forma que desees y que mejor se acomode a tus necesidades.\n\n•Transportable: su bolso de 70cm X 10cm y su peso de 6,5 Kg te permitirá transportarlo adónde desees sin problemas.\n\n•Todo terreno: su doble sistema de anclaje es ideal para armarlo en cualquier superficie, sin importar el tipo de suelo ni los desniveles.\n\n•Resistente al clima: sus estacas tirabuzón le permite soportar vientos muy fuertes. Ampliamente probado en las cosas argentinas!!\n\n•Sencillo y sin mantenimiento: Ninguna de sus piezas necesita mantenimiento. Además no posee piezas móviles, lo que reduce ampliamente el riesgo de roturas, permitiendo una vida útil súper larga.\nSus parantes son de aluminio, lo que evita la oxidación y deterioro.\n\n•Rápido y práctico: su armado se puede realizar por una sola persona, sin tomar más de 5 minutos para esto.",
      price: "450000.00",
      stock: 5,
      color: "Verde",
      size: "Grande",
      marca: "AWA",
      material: "Aluminio",
      materialTela: "Tela elástica UV",
      impermeable: "Si",
      ajustable: "Si",
      category: "PREMIUN 3X3",
      peso: "6500.00",
      deleted: false,
      averageScore: 0,
      countReviews: 0,
      images: [
        Premium1,
        Premium2,
        Premium3
      ]
    },
    {
    "id": 5,
    "name": "Gazebo Modelo Mini",
    "image": TurquesaPortada,
    "description": "Modelo Mini:\n-tela 1,5X2m (armado queda de 2x3 aprox)\n-2 Parantes regulables (1,7 altura máxima) (opcional 2 parantes más extras.)\n-4 estacas tirabuzón\n-4 bolsas de contrapeso.\n- bolso de transporte.\n\nDescuentos pagando por efectivo/transferencia.\n•Multiforma: su toldo elástico, y sus parantes regulables en altura te permitirán darle la forma que desees y que mejor se acomode a tus necesidades.\n\n•Transportable: su bolso de 70cm X 10cm y su peso de 6,5 Kg te permitirá transportarlo adónde desees si problemas.\n\n•Todo terreno: su doble sistema de anclaje es ideal para armarlo en cualquier superficie, sin importar el tipo de suelo ni los desniveles.\n\n•Resistente al clima: sus estacas tirabuzón le permite soportar vientos muy fuertes. Ampliamente probado en las cosas argentinas!!\n\n•Sencillo y sin mantenimiento: Ninguna de sus piezas necesita mantenimiento. Además no posee piezas móviles, lo que reduce ampliamente el riesgo de roturas, permitiendo una vida útil súper larga.\nSus parantes son de aluminio, lo que evita la oxidación y deterioro.\n\n•Rápido y práctico: su armado se puede realizar por una sola persona, sin tomar más de 5 minutos para esto.\n",
    "price": "320000.00",
    "stock": 5,
    "color": "Otro",
    "size": "Mini",
    "marca": "AWA",
    "material": "Aluminio",
    "materialTela": "Tela elástica UV",
    "impermeable": "Si",
    "ajustable": "Si",
    "category": "Mini",
    "peso": "6.00",
    "deleted": false,
    "averageScore": 0,
    "countReviews": 0,
    "images": [
      Turquesa12,
      Turquesa2,
    ],
    "Images": []
    },
    {
      "id": 6,
      "name": "Gazebo Modelo Celeste",
      "image": CelestePortada,
      "description": "Modelo Celeste:\n-Tela elastica 3x3m (armado queda de 5x5m aprox)\n-4 Parantes de aluminio regulables (2,25m altura máxima)\n-4 estacas tirabuzón\n-4 bolsas de contrapeso\n- bolso de transporte\n\nDescuentos pagando por efectivo/transferencia.\n\n•Multiforma: su toldo elástico, y sus parantes regulables en altura te permitirán darle la forma que desees y que mejor se acomode a tus necesidades.\n\n•Transportable: su bolso de 70cm X 10cm y su peso de 6,5 Kg te permitirá transportarlo adónde desees si problemas.\n\n•Todo terreno: su doble sistema de anclaje es ideal para armarlo en cualquier superficie, sin importar el tipo de suelo ni los desniveles.\n\n•Resistente al clima: sus estacas tirabuzón le permite soportar vientos muy fuertes. Ampliamente probado en las cosas argentinas!!\n\n•Sencillo y sin mantenimiento: Ninguna de sus piezas necesita mantenimiento. Además no posee piezas móviles, lo que reduce ampliamente el riesgo de roturas, permitiendo una vida útil súper larga.\nSus parantes son de aluminio, lo que evita la oxidación y deterioro.\n\n•Rápido y práctico: su armado se puede realizar por una sola persona, sin tomar más de 5 minutos para esto.",
      "price": "450000.00",
      "stock": 5,
      "color": "Celeste",
      "size": "Grande",
      "marca": "AWA",
      "material": "Aluminio",
      "materialTela": "Tela elástica UV",
      "impermeable": "Si",
      "ajustable": "Si",
      "category": "PREMIUN 3X3",
      "peso": "6500.00",
      "deleted": false,
      "averageScore": 0,
      "countReviews": 0,
      "images": [
        Celeste1,
        Celeste2,
        Celeste3
      ],
      "Images": []
    },
    {
    "id": 7,
    "name": "Gazebo Modelo Rojo",
    "image": RojoPortada,
    "description": "Modelo Mini:\n-tela 1,5X2m (armado queda de 2x3 aprox)\n-2 Parantes regulables (1,7 altura máxima) (opcional 2 parantes más extras.)\n-4 estacas tirabuzón\n-4 bolsas de contrapeso.\n- bolso de transporte.\n\nDescuentos pagando por efectivo/transferencia.\n•Multiforma: su toldo elástico, y sus parantes regulables en altura te permitirán darle la forma que desees y que mejor se acomode a tus necesidades.\n\n•Transportable: su bolso de 70cm X 10cm y su peso de 6,5 Kg te permitirá transportarlo adónde desees si problemas.\n\n•Todo terreno: su doble sistema de anclaje es ideal para armarlo en cualquier superficie, sin importar el tipo de suelo ni los desniveles.\n\n•Resistente al clima: sus estacas tirabuzón le permite soportar vientos muy fuertes. Ampliamente probado en las cosas argentinas!!\n\n•Sencillo y sin mantenimiento: Ninguna de sus piezas necesita mantenimiento. Además no posee piezas móviles, lo que reduce ampliamente el riesgo de roturas, permitiendo una vida útil súper larga.\nSus parantes son de aluminio, lo que evita la oxidación y deterioro.\n\n•Rápido y práctico: su armado se puede realizar por una sola persona, sin tomar más de 5 minutos para esto.\n",
    "price": "320000.00",
    "stock": 5,
    "color": "Rojo",
    "size": "Mini",
    "marca": "AWA",
    "material": "Aluminio",
    "materialTela": "Tela elástica UV",
    "impermeable": "Si",
    "ajustable": "Si",
    "category": "Mini",
    "peso": "6.00",
    "deleted": false,
    "averageScore": 0,
    "countReviews": 0,
    "images": [
      Rojo1,
      Rojo2,
      Rojo3
    ],
    "Images": []
    },
  ]

// export const gazebos = [
//   {
//     id: 1,
//     name: "Gazebo de Jardín Rojo 3x3m",
//     image: "https://example.com/gazebo-rojo-3x3.jpg",
//     description: "Gazebo de jardín de 3x3 metros, color rojo, ideal para eventos al aire libre.",
//     price: 149.99,
//     stock: 10,
//     color: "Rojo",
//     size: "3x3m",
//     material: "Acero",
//     materialTela: "Poliéster",
//     category: "Jardín",
//     deleted: false,
//     averageScore: 4.5,
//     countReviews: 15,
//     images: ["https://example.com/gazebo-rojo-3x3-1.jpg", "https://example.com/gazebo-rojo-3x3-2.jpg"],
//   },
//   {
//     id: 2,
//     name: "Gazebo Plegable Azul 4x4m",
//     image: "https://example.com/gazebo-azul-4x4.jpg",
//     description: "Gazebo plegable de 4x4 metros en color azul, resistente y fácil de montar.",
//     price: 199.99,
//     stock: 8,
//     color: "Azul",
//     size: "4x4m",
//     material: "Aluminio",
//     materialTela: "PVC",
//     category: "Eventos",
//     deleted: false,
//     averageScore: 4.7,
//     countReviews: 20,
//     images: ["https://example.com/gazebo-azul-4x4-1.jpg", "https://example.com/gazebo-azul-4x4-2.jpg"],
//   },
//   {
//     id: 3,
//     name: "Gazebo de Playa Naranja 2.5x2.5m",
//     image: "https://example.com/gazebo-naranja-2.5x2.5.jpg",
//     description: "Perfecto para la playa, este gazebo naranja de 2.5x2.5 metros ofrece sombra y comodidad.",
//     price: 129.99,
//     stock: 15,
//     color: "Naranja",
//     size: "2.5x2.5m",
//     material: "Acero",
//     materialTela: "Nylon",
//     category: "Playa",
//     deleted: false,
//     averageScore: 4.2,
//     countReviews: 10,
//     images: ["https://example.com/gazebo-naranja-2.5x2.5-1.jpg", "https://example.com/gazebo-naranja-2.5x2.5-2.jpg"],
//   },
//   {
//     id: 4,
//     name: "Gazebo Impermeable Amarillo 5x5m",
//     image: "https://example.com/gazebo-amarillo-5x5.jpg",
//     description: "Gazebo amarillo de 5x5 metros, impermeable y perfecto para grandes eventos.",
//     price: 299.99,
//     stock: 5,
//     color: "Amarillo",
//     size: "5x5m",
//     material: "Aluminio",
//     materialTela: "Poliéster Reforzado",
//     category: "Eventos",
//     deleted: false,
//     averageScore: 4.9,
//     countReviews: 25,
//     images: ["https://example.com/gazebo-amarillo-5x5-1.jpg", "https://example.com/gazebo-amarillo-5x5-2.jpg"],
//   },
//   {
//     id: 5,
//     name: "Gazebo de Camping Rojo 2x2m",
//     image: "https://example.com/gazebo-rojo-2x2.jpg",
//     description: "Compacto y ligero, este gazebo rojo de 2x2 metros es ideal para camping.",
//     price: 99.99,
//     stock: 12,
//     color: "Rojo",
//     size: "2x2m",
//     material: "Fibra de Vidrio",
//     materialTela: "Poliéster",
//     category: "Camping",
//     deleted: false,
//     averageScore: 4.0,
//     countReviews: 5,
//     images: ["https://example.com/gazebo-rojo-2x2-1.jpg", "https://example.com/gazebo-rojo-2x2-2.jpg"],
//   },
//   {
//     id: 6,
//     name: "Gazebo para Fiesta Azul 6x6m",
//     image: "https://example.com/gazebo-azul-6x6.jpg",
//     description: "Amplio gazebo azul de 6x6 metros, ideal para fiestas y eventos al aire libre.",
//     price: 399.99,
//     stock: 3,
//     color: "Azul",
//     size: "6x6m",
//     material: "Acero",
//     materialTela: "PVC",
//     category: "Fiesta",
//     deleted: false,
//     averageScore: 4.8,
//     countReviews: 30,
//     images: ["https://example.com/gazebo-azul-6x6-1.jpg", "https://example.com/gazebo-azul-6x6-2.jpg"],
//   },
//   {
//     id: 7,
//     name: "Gazebo Económico Naranja 3.5x3.5m",
//     image: "http://res.cloudinary.com/djsqt7j6v/image/upload/v1720811163/lrt7keghnxyt8e6vkxv9.jpg",
//     description: "Gazebo económico de 3.5x3.5 metros en color naranja, fácil de montar.",
//     price: 119.99,
//     stock: 20,
//     color: "Naranja",
//     size: "3.5x3.5m",
//     material: "Acero",
//     materialTela: "Nylon",
//     category: "Jardín",
//     deleted: false,
//     averageScore: 4.1,
//     countReviews: 8,
//     images: ["https://example.com/gazebo-naranja-3.5x3.5-1.jpg", "https://example.com/gazebo-naranja-3.5x3.5-2.jpg"],
//   },
//   {
//     id: 8,
//     name: "Gazebo de Lujo Amarillo 4.5x4.5m",
//     image: "https://example.com/gazebo-amarillo-4.5x4.5.jpg",
//     description: "Gazebo de lujo de 4.5x4.5 metros en color amarillo, con materiales premium.",
//     price: 349.99,
//     stock: 6,
//     color: "Amarillo",
//     size: "4.5x4.5m",
//     material: "Aluminio",
//     materialTela: "Poliéster Reforzado",
//     category: "Eventos",
//     deleted: false,
//     averageScore: 4.9,
//     countReviews: 18,
//     images: ["https://example.com/gazebo-amarillo-4.5x4.5-1.jpg", "https://example.com/gazebo-amarillo-4.5x4.5-2.jpg"],
//   },
//   {
//     id: 9,
//     name: "Gazebo Deportivo Rojo 3x4m",
//     image: "https://example.com/gazebo-rojo-3x4.jpg",
//     description: "Ideal para eventos deportivos, este gazebo rojo de 3x4 metros ofrece amplio espacio.",
//     price: 169.99,
//     stock: 9,
//     color: "Rojo",
//     size: "3x4m",
//     material: "Acero",
//     materialTela: "PVC",
//     category: "Deportivo",
//     deleted: false,
//     averageScore: 4.6,
//     countReviews: 12,
//     images: ["https://example.com/gazebo-rojo-3x4-1.jpg", "https://example.com/gazebo-rojo-3x4-2.jpg"],
//   },
//   {
//     id: 10,
//     name: "Gazebo Familiar Azul 5x5m",
//     image: "https://example.com/gazebo-azul-5x5.jpg",
//     description: "Gazebo familiar de 5x5 metros en color azul, perfecto para reuniones y fiestas.",
//     price: 279.99,
//     stock: 7,
//     color: "Azul",
//     size: "5x5m",
//     material: "Fibra de Vidrio",
//     materialTela: "Poliéster",
//     category: "Familia",
//     deleted: false,
//     averageScore: 4.7,
//     countReviews: 22,
//     images: ["https://example.com/gazebo-azul-5x5-1.jpg", "https://example.com/gazebo-azul-5x5-2.jpg"],
//   }
// ];


