const dummyData = [
    {
      name: "Artículo 1",
      image: "imagen_1.jpg",
      description: "Descripción del artículo 1.",
      price: 19.99,
      stock: 50,
      size: "M",
      material: "Algodón",
      category: "Ropa",
    },
    {
      name: "Artículo 2",
      image: "imagen_2.jpg",
      description: "Descripción del artículo 2.",
      price: 29.99,
      stock: 30,
      size: "L",
      material: "Cuero",
      category: "Calzado",
    },
    {
      name: "Artículo 3",
      image: "imagen_3.jpg",
      description: "Descripción del artículo 3.",
      price: 39.99,
      stock: 20,
      size: "S",
      material: "Plástico",
      category: "Accesorios",
    },
    {
      name: "Artículo 4",
      image: "imagen_4.jpg",
      description: "Descripción del artículo 4.",
      price: 49.99,
      stock: 10,
      size: "XL",
      material: "Metal",
      category: "Electrónicos",
    },
    {
      name: "Artículo 5",
      image: "imagen_5.jpg",
      description: "Descripción del artículo 5.",
      price: 59.99,
      stock: 15,
      size: "M",
      material: "Lana",
      category: "Ropa",
    },
  ];
  
  module.exports = dummyData;
  